# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('index', models.CharField(max_length=5)),
                ('people', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('arxiv', models.CharField(blank=True, max_length=200, null=True)),
                ('arxivlink', models.TextField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('hyperlink', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Post-Doc', 'Post-Doc'), ('Professor', 'Professor'), ('Research Professor', 'Research Professor'), ('Alumni', 'Alumni')], max_length=30)),
                ('index', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=20)),
                ('link', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'Peoples',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.CharField(max_length=50)),
                ('date_end', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(max_length=50)),
                ('lecturer', models.CharField(max_length=100)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_link', models.TextField(blank=True, null=True)),
                ('schedule', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seminar',
                'verbose_name_plural': 'Seminars',
            },
        ),
    ]
