# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEP_COSMO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('U', 'Undergraduate'), ('G', 'Graduate'), ('PD', 'Post-Doc'), ('P', 'Professor'), ('RP', 'Research Professor'), ('Al', 'Alumni')], max_length=30)),
                ('index', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=20)),
                ('link', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Peoples',
                'verbose_name': 'People',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='arxiv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='arxivlink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='hyperlink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
