# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEP_COSMO', '0002_auto_20170517_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Post-Doc', 'Post-Doc'), ('Professor', 'Professor'), ('Research Professor', 'Research Professor'), ('Alumni', 'Alumni')], max_length=30),
        ),
    ]
