# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEP_COSMO', '0002_seminar_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
