# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HEP_COSMO', '0003_seminar_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('dateAndPlace', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=100)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_link', models.TextField(blank=True, null=True)),
                ('img_link', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snail Lecture',
                'verbose_name_plural': 'Snail Lectures',
            },
        ),
        migrations.AlterField(
            model_name='people',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
